name: flutter_cloud_kit
description: Plugin for interaction with Apple CloudKit
version: 0.0.4
homepage: https://github.com/Inigrey/flutter_cloud_kit

environment:
  sdk: '>=3.5.1 <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterCloudKitPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: FlutterCloudKitPlugin
        sharedDarwinSource: true
